CI: Lint OpenAPI spec by trying to generate a Ruby client. RD-23141 (#99)

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -19,4 +19,20 @@ jobs:
       uses: actions/checkout@v2
     - name: Run tests
       run: go test -v -covermode=count ./...
-
+  lint:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v3
+    - uses: actions/setup-node@v3
+      with:
+        node-version: 16
+    - run: |
+        out=$(npx @openapitools/openapi-generator-cli generate -i specs/engage-digital_openapi3.yaml -g ruby -o /tmp/test/ | fgrep "[main]" | fgrep -v "INFO" | grep -v "^#" || :)
+        if [ -z "$out" ]
+        then
+          echo "No error"
+          exit 0
+        else
+          echo $out
+          exit -1
+        fi
